export { default as css } from "./css.png";
export { default as docker } from "./docker.png";
export { default as git } from "./git.png";
export { default as nodejs } from "./nodejs.png";
export { default as reactjs } from "./reactjs.png";
export { default as typescript } from "./typescript.png";
export { default as webpack } from "./webpack.png";
export { default as cpp } from "./cpp.png";
export { default as c } from "./c.png";
