export * from "./Works";
export * from "./StarCanvas";
export * from "./Feedbacks";
export * from "./Experience";
export * from "./Contact";
export * from "./About";
export * from "./Tech";
export * from "./Navbar";
export * from "./Hero";
